((nil . ((compile-command . "make")
         (indent-tabs-mode . nil)
         (fill-column . 80)
         (tab-width . 4)
         (no-clang-format . t)
         (helm-make-arguments . "-j4")
         (clang-company-arguments . "-std=c++11")
         (flycheck-clang-language-standard . "-std=c++11")
         (flycheck-gcc-language-standard . "-std=c++11")))
 (makefile-automake-mode . ((indent-tabs-mode . t)))
 (c-mode . ((c-file-style . "BSD")
            (c-basic-offset . 4)))
 (c++-mode . ((c-file-style . "BSD")
              (c-basic-offset . 4))))
