#!/bin/bash

# PID to profile.
ALL=0
PID=
MATCH=
TIME=60
while getopts ":am:p:t:x" opt; do
  case $opt in
    a) ALL=1 ;;
    m) MATCH="$OPTARG" ;;
    p) PID="$OPTARG" ;;
    t) TIME="$OPTARG" ;;
    x) set -x ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done
shift $((OPTIND - 1))

CMD=(perf record
     -g
     --call-graph dwarf
     -F 101
    )

if [ "$ALL" -eq 1 ]; then
  CMD+=(-a)
elif [ -n "$PID" ]; then
  CMD+=(-p "$PID")
else
  echo "Error: You must use -a or -p PID"
  exit 1
fi

"${CMD[@]}" "$@" -- sleep "$TIME"

perf script 2>/dev/null | stackcollapse-perf.pl --all > /tmp/collapse.txt

# very hacky
if [ -n "$MATCH" ]; then
  sed -i "/$MATCH/p" /tmp/collapse.txt
fi
